### ISSUE TITLE
Implement ranked season 13 reward

### ISSUE THREAD

**Issue by DoctorGester** [DoctorGester/crumbling-island-arena#81]
Set suggestions welcome

**Comment by C039ATeJL** [comment]
Select a reward in the official VK group

**Comment by Chiyukii** [comment]
TA: http://dota2.gamepedia.com/Province_of_the_Psion_Inquisitor
PA: http://dota2.gamepedia.com/Toll_of_the_Fearful_Aria
Tinker: http://dota2.gamepedia.com/Submerged_Hazard
Maybe something like that ?

**Comment by vocalpocal** [comment]
http://dota2.gamepedia.com/Vermillion_Crucible
http://dota2.gamepedia.com/Guise_of_the_Winged_Bolt
Kappa

on a more serious note, maybe Sniper set?
This one fits alright with the pass reward immortal I think http://dota2.gamepedia.com/Hinterland_Stalker

**Comment by C039ATeJL** [comment]
Anti mage http://dota2.gamepedia.com/Guilt_of_the_Survivor

**Comment by C039ATeJL** [comment]
Rubick(жаль что его нет в игре) http://dota2.gamepedia.com/Fantoccini%27s_Dilemma

**Comment by PotatoLordX1** [comment]
give earth spirit some love http://dota2.gamepedia.com/The_Jade_General

**Comment by 13lackHawk** [comment]
I dont like the Psion Inquisitor TA set because her hair is completely hidden. This one is looks much better for me: http://dota2.gamepedia.com/Clandestine_Trail

PL(want the most): http://dota2.gamepedia.com/Vengeance_of_the_Sunwarrior
QOP: http://dota2.gamepedia.com/Raiments_of_Twilight_Shade + Bloodfeather Wings 
AM: http://dota2.gamepedia.com/Guilt_of_the_Survivor
Ursa: http://dota2.gamepedia.com/The_Alpine_Stalker%27s_Set :D
CM: http://dota2.gamepedia.com/Lady_of_the_Lumini_Polare
Brew: http://dota2.gamepedia.com/Rumrunner%27s_Carronade
Drow: http://dota2.gamepedia.com/Guise_of_the_Winged_Bolt

**Comment by C039ATeJL** [comment]
QOP: http://dota2-ru.gamepedia.com/Набор_«Delightful_Affliction»
Storm Spirit: http://dota2.gamepedia.com/Corridan_Maestro
jugg: http://dota2.gamepedia.com/Bladeform_Legacy (да, я знаю что на джагера уже был сет)
